 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/book_users", type: :request do
  
  # BookUser. As you add validations to BookUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BookUser.create! valid_attributes
      get book_users_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      book_user = BookUser.create! valid_attributes
      get book_user_url(book_user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_book_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      book_user = BookUser.create! valid_attributes
      get edit_book_user_url(book_user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BookUser" do
        expect {
          post book_users_url, params: { book_user: valid_attributes }
        }.to change(BookUser, :count).by(1)
      end

      it "redirects to the created book_user" do
        post book_users_url, params: { book_user: valid_attributes }
        expect(response).to redirect_to(book_user_url(BookUser.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BookUser" do
        expect {
          post book_users_url, params: { book_user: invalid_attributes }
        }.to change(BookUser, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post book_users_url, params: { book_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested book_user" do
        book_user = BookUser.create! valid_attributes
        patch book_user_url(book_user), params: { book_user: new_attributes }
        book_user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the book_user" do
        book_user = BookUser.create! valid_attributes
        patch book_user_url(book_user), params: { book_user: new_attributes }
        book_user.reload
        expect(response).to redirect_to(book_user_url(book_user))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        book_user = BookUser.create! valid_attributes
        patch book_user_url(book_user), params: { book_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested book_user" do
      book_user = BookUser.create! valid_attributes
      expect {
        delete book_user_url(book_user)
      }.to change(BookUser, :count).by(-1)
    end

    it "redirects to the book_users list" do
      book_user = BookUser.create! valid_attributes
      delete book_user_url(book_user)
      expect(response).to redirect_to(book_users_url)
    end
  end
end
